version: 2.1

jobs:
  build:
    docker:
      - image:  circleci/node:4.8.2
    steps:
      - checkout 
      - run:
          name: Start Application
          command: cd multi && npm install &&  node index.js

workflows:
  version: 2
  run_now:
    jobs:
      - build
