version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
            source ~/.bashrc
            cd multi
            npm install
          # Add a separate step for the npm start command
      - run:
          name: Start Application
          command: node index.js

workflows:
  version: 2
  run_now:
    jobs:
      - build
